#pragma once

typedef enum { UP, DOWN, LEFT, RIGTH, NONE } DIRECTION;
typedef unsigned char UCHAR;

#define FIELD_SIZE 30
#define DEFAULT_CAPACITY 300

#define BONUS_TIME 160000

#define SNAKE_COLOR BG_GREEN
#define SNAKE_COLOR_INTENSITY BG_INTENSITY_GREEN
#define MAP_COLOR BG_RED
#define MAP_COLOR_INTENSITY BG_INTENSITY_RED
#define BORDER_COLOR BG_WHITE
#define BORDER_COLOR_INTENSITY BG_INTENSITY_WHITE
#define BONUS_COLOR BG_WHITE

#define WALL_CELL '1'
#define EMPTY_CELL '0'